#ifndef	STPP_VERSION_INCLUDED
#define STPP_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define STPP_VERSION_MAJOR	1
#define STPP_VERSION_MINOR	1
#define STPP_VERSION_PATCH	11
#define STPP_VERSION_BETA	0
#define STPP_VERSION_VERSTRING	MAKE_STR(STPP_VERSION_MAJOR) "." MAKE_STR(STPP_VERSION_MINOR) "." MAKE_STR(STPP_VERSION_PATCH) "." MAKE_STR(STPP_VERSION_BETA)

#endif
